# 1일차 Review : 같은 문제 다시 풀어보기

    학습은 10번으로!

In [1]:
from sklearn.datasets import load_boston

In [2]:
boston = load_boston()

C:\Users\User\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (i

In [3]:
x = boston.data
y = boston.target

In [4]:
x.shape, y.shape

((506, 13), (506,))

In [6]:
#####################
# 라이브러리 불러오기
#####################
import tensorflow as tf
from tensorflow import keras

import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split

In [7]:
x_train, x_test, y_train, y_test = train_test_split(x,y,random_state=2022,test_size=0.2)

In [9]:
x_train.shape, y_train.shape

((404, 13), (404,))

In [12]:
########
# 모델링
########
keras.backend.clear_session()

model = keras.models.Sequential()

model.add(keras.layers.Input(shape=(13,)))
model.add(keras.layers.Dense(1))

model.compile(loss='mse', optimizer = keras.optimizers.Adam(learning_rate=0.1))

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 1)                 14        
                                                                 
Total params: 14
Trainable params: 14
Non-trainable params: 0
_________________________________________________________________


In [13]:
###########
# 모델 학습
###########

model.fit(x_train, y_train, epochs=10, verbose = 1)

Epoch 1/10
13/13 [==============================] - 0s 2ms/step - loss: 1261.3632
Epoch 2/10
13/13 [==============================] - 0s 2ms/step - loss: 322.5361
Epoch 3/10
13/13 [==============================] - 0s 2ms/step - loss: 111.3813
Epoch 4/10
13/13 [==============================] - 0s 2ms/step - loss: 84.2896
Epoch 5/10
13/13 [==============================] - 0s 2ms/step - loss: 68.7363
Epoch 6/10
13/13 [==============================] - 0s 2ms/step - loss: 64.3600
Epoch 7/10
13/13 [==============================] - 0s 2ms/step - loss: 64.9117
Epoch 8/10
13/13 [==============================] - 0s 2ms/step - loss: 73.2661
Epoch 9/10
13/13 [==============================] - 0s 2ms/step - loss: 57.7467
Epoch 10/10
13/13 [==============================] - 0s 2ms/step - loss: 58.5240


In [14]:
###########
# 모델 예측
###########
y_pred = model.predict(x_test)


In [15]:
y_pred[:5].reshape(-1)

array([23.044867, 16.899492, 24.286055, 30.926708, 21.103159],
      dtype=float32)

In [16]:
y[:5].reshape(-1)

array([24. , 21.6, 34.7, 33.4, 36.2])

# 히든 레이어 추가하여 모델링!

    히든 레이어 2개를 추가하여 다시 모델링!
    히든 레이어 노드 수 : 32
    히든 레이어 activation = 'relu'

In [40]:
########
# 모델링
########
keras.backend.clear_session()

model = keras.models.Sequential()

model.add(keras.layers.Input(shape=(13,), name = 'input_layer'))
model.add(keras.layers.Dense(32, activation='relu'))
model.add(keras.layers.Dense(32, activation='relu'))
model.add(keras.layers.Dense(1, name = 'output_layer'))


model.compile(loss='mse', optimizer = keras.optimizers.Adam(learning_rate=0.1))

model.summary()


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 32)                448       
                                                                 
 dense_1 (Dense)             (None, 32)                1056      
                                                                 
 output_layer (Dense)        (None, 1)                 33        
                                                                 
Total params: 1,537
Trainable params: 1,537
Non-trainable params: 0
_________________________________________________________________


In [43]:
###########
# 모델 학습
###########
model.fit(x_train, y_train, epochs=10, verbose = 1)


Epoch 1/10
13/13 [==============================] - 0s 2ms/step - loss: 80.7876
Epoch 2/10
13/13 [==============================] - 0s 3ms/step - loss: 90.3027
Epoch 3/10
13/13 [==============================] - 0s 2ms/step - loss: 93.5223
Epoch 4/10
13/13 [==============================] - 0s 3ms/step - loss: 107.9124
Epoch 5/10
13/13 [==============================] - 0s 2ms/step - loss: 230.2717
Epoch 6/10
13/13 [==============================] - 0s 3ms/step - loss: 214.7758
Epoch 7/10
13/13 [==============================] - 0s 2ms/step - loss: 144.3177
Epoch 8/10
13/13 [==============================] - 0s 2ms/step - loss: 103.5255
Epoch 9/10
13/13 [==============================] - 0s 2ms/step - loss: 85.3660
Epoch 10/10
13/13 [==============================] - 0s 2ms/step - loss: 85.6032


In [44]:
###########
# 모델 예측
###########
y_pred = model.predict(x_test)
y_pred[:5].reshape(-1)

array([20.739744, 15.409035, 16.630804, 25.62538 , 13.350184],
      dtype=float32)

In [39]:
y[:5].reshape(-1)

array([24. , 21.6, 34.7, 33.4, 36.2])