# 1일차 Review : 같은 문제 다시 풀어보기

    학습은 10번으로!

In [36]:
from sklearn.datasets import load_breast_cancer

In [37]:
cancer = load_breast_cancer()

In [38]:
x = cancer.data
y = cancer.target

In [39]:
x.shape, y.shape

((569, 30), (569,))

In [40]:
#####################
# 라이브러리 불러오기
#####################
import tensorflow as tf
from tensorflow import keras

import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split


In [41]:
x_train, x_test, y_train, y_test = train_test_split(x,y,random_state=2022,test_size=0.2)

In [42]:
x_train.shape, y_train.shape

((455, 30), (455,))

In [8]:
########
# 모델링
########
keras.backend.clear_session()

il = keras.layers.Input(shape = (30,))
ol = keras.layers.Dense(1,activation = 'sigmoid')(il)

model = keras.models.Model(il, ol)

model.compile(loss='binary_crossentropy', optimizer = keras.optimizers.Adam(learning_rate=0.1),
             metrics = ['accuracy'])

model.summary()


Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 30)]              0         
                                                                 
 dense (Dense)               (None, 1)                 31        
                                                                 
Total params: 31
Trainable params: 31
Non-trainable params: 0
_________________________________________________________________


In [16]:
###########
# 모델 학습
###########
model.fit(x_train, y_train, epochs=10, verbose = 1, validation_split=0.2)


Epoch 1/10
12/12 [==============================] - 0s 13ms/step - loss: 1.2110 - accuracy: 0.8874 - val_loss: 0.7239 - val_accuracy: 0.9451
Epoch 2/10
12/12 [==============================] - 0s 7ms/step - loss: 1.1604 - accuracy: 0.8984 - val_loss: 0.3110 - val_accuracy: 0.9451
Epoch 3/10
12/12 [==============================] - 0s 7ms/step - loss: 0.6488 - accuracy: 0.9093 - val_loss: 0.3425 - val_accuracy: 0.9560
Epoch 4/10
12/12 [==============================] - 0s 7ms/step - loss: 0.6924 - accuracy: 0.9258 - val_loss: 0.6605 - val_accuracy: 0.8791
Epoch 5/10
12/12 [==============================] - 0s 7ms/step - loss: 0.5201 - accuracy: 0.9341 - val_loss: 0.3649 - val_accuracy: 0.9560
Epoch 6/10
12/12 [==============================] - 0s 7ms/step - loss: 1.4254 - accuracy: 0.8791 - val_loss: 1.4173 - val_accuracy: 0.8571
Epoch 7/10
12/12 [==============================] - 0s 7ms/step - loss: 1.1426 - accuracy: 0.8956 - val_loss: 0.1003 - val_accuracy: 0.9890
Epoch 8/10
12/12 [=

In [17]:
###########
# 모델 예측
###########
y_pred = model.predict(x_test)
y_pred[:5].reshape(-1)

array([1., 1., 1., 1., 1.], dtype=float32)

In [15]:
y_test[:5]

array([1, 1, 0, 1, 1])

# 히든 레이어 추가하여 모델링!

    히든 레이어 2개를 추가하여 다시 모델링!
    히든 레이어 노드 수 : 32
    히든 레이어 activation = 'relu'

In [62]:
########
# 모델링
########
keras.backend.clear_session()

il = keras.layers.Input(shape = (30,))
ol_1 = keras.layers.Dense(32, activation='relu')(il)
ol_2 = keras.layers.Dense(32, activation='relu')(ol_1)
ol = keras.layers.Dense(1,activation = 'sigmoid')(ol_2)

model = keras.models.Model(il, ol)

model.compile(loss='binary_crossentropy', optimizer = 'adam',
             metrics = ['accuracy'])

model.summary()



Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 30)]              0         
                                                                 
 dense (Dense)               (None, 32)                992       
                                                                 
 dense_1 (Dense)             (None, 32)                1056      
                                                                 
 dense_2 (Dense)             (None, 1)                 33        
                                                                 
Total params: 2,081
Trainable params: 2,081
Non-trainable params: 0
_________________________________________________________________


In [67]:
from tensorflow.keras.utils import plot_model

In [63]:
###########
# 모델 학습
###########
model.fit(x_train, y_train, epochs=10, verbose = 1, validation_split=0.2)

Epoch 1/10
12/12 [==============================] - 1s 24ms/step - loss: 46.5856 - accuracy: 0.3791 - val_loss: 6.5623 - val_accuracy: 0.3187
Epoch 2/10
12/12 [==============================] - 0s 7ms/step - loss: 7.3057 - accuracy: 0.6429 - val_loss: 0.3531 - val_accuracy: 0.8462
Epoch 3/10
12/12 [==============================] - 0s 6ms/step - loss: 1.9801 - accuracy: 0.6264 - val_loss: 0.6246 - val_accuracy: 0.8462
Epoch 4/10
12/12 [==============================] - 0s 6ms/step - loss: 0.8558 - accuracy: 0.8324 - val_loss: 0.4735 - val_accuracy: 0.8242
Epoch 5/10
12/12 [==============================] - 0s 7ms/step - loss: 0.3452 - accuracy: 0.8956 - val_loss: 0.1158 - val_accuracy: 0.9560
Epoch 6/10
12/12 [==============================] - 0s 6ms/step - loss: 0.3333 - accuracy: 0.9011 - val_loss: 0.1178 - val_accuracy: 0.9560
Epoch 7/10
12/12 [==============================] - 0s 7ms/step - loss: 0.3384 - accuracy: 0.8929 - val_loss: 0.1133 - val_accuracy: 0.9560
Epoch 8/10
12/12 [

In [65]:
###########
# 모델 예측
###########
y_pred = model.predict(x_test)
y_pred[:5].reshape(-1)


array([0.94103825, 0.99613976, 0.9672679 , 0.9955513 , 0.98794496],
      dtype=float32)

In [66]:
y_test[:5]

array([1, 1, 0, 1, 1])